name: portfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  flutter_web_browser: any
  responsive_framework: ^0.1.5
  resize: ^1.0.0
  mailto: ^2.0.0
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/profile.png
    - assets/icons/eureka-logo.png
    - assets/icons/firebase-logo.png
    - assets/icons/flutter-logo.png
    - assets/icons/node-logo.png
    - assets/icons/postgres-logo.png
    - assets/icons/typescript-logo.png
    - assets/byu-logo.png
    - assets/creators.png
    - assets/icons/vue-logo.png
    - assets/icons/javascript-logo.png
    - assets/wya.png
    - assets/icons/cpp-logo.png
    - assets/icons/data-structures.png
    - assets/icons/discrete-math.png
    - assets/icons/oop.png
    - assets/icons/web-dev.png
    - assets/icons/nuxt.png
    - assets/icons/database.png
    - assets/icons/expressjs.png
    - assets/icons/ExpressJS-logo.png
    - assets/aws.png
    - assets/icons/dart.png
    - assets/icons/github.png
    - assets/icons/sql.png
    - assets/icons/html-css.png
    - assets/sava.png
    - assets/icons/npm.png

    - build/flutter_assets/assets/logo.png
    - build/flutter_assets/assets/profile.png
    - build/flutter_assets/assets/icons/eureka-logo.png
    - build/flutter_assets/assets/icons/firebase-logo.png
    - build/flutter_assets/assets/icons/flutter-logo.png
    - build/flutter_assets/assets/icons/node-logo.png
    - build/flutter_assets/assets/icons/postgres-logo.png
    - build/flutter_assets/assets/icons/typescript-logo.png
    - build/flutter_assets/assets/byu-logo.png
    - build/flutter_assets/assets/creators.png
    - build/flutter_assets/assets/icons/vue-logo.png
    - build/flutter_assets/assets/icons/javascript-logo.png
    - build/flutter_assets/assets/wya.png
    - build/flutter_assets/assets/icons/cpp-logo.png
    - build/flutter_assets/assets/icons/data-structures.png
    - build/flutter_assets/assets/icons/discrete-math.png
    - build/flutter_assets/assets/icons/oop.png
    - build/flutter_assets/assets/icons/web-dev.png
    - build/flutter_assets/assets/icons/nuxt.png
    - build/flutter_assets/assets/icons/database.png
    - build/flutter_assets/assets/icons/expressjs.png
    - build/flutter_assets/assets/icons/ExpressJS-logo.png
    - build/flutter_assets/assets/aws.png
    - build/flutter_assets/assets/icons/dart.png
    - build/flutter_assets/assets/icons/github.png
    - build/flutter_assets/assets/icons/sql.png
    - build/flutter_assets/assets/icons/html-css.png
    - build/flutter_assets/assets/sava.png
    - build/flutter_assets/assets/icons/npm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
